### PR TITLE
chore: Cleanup some compile flags; remove portaudio.

### PR DESCRIPTION
**Pull request by iphydf**
We weren't using portaudio anymore.

- - -
This change is [Reviewable](https://reviewable.io/reviews/TokTok/toktok-stack/677)

### CODE REVIEW

**Comment by iphydf** [comment]
It's for `PATH_MAX`, `strcasecmp`, `strdup`, and various other gnu or POSIX functions.

**Review by Green-Sky — CHANGES_REQUESTED** [review]
> Reviewed 42 of 42 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TokTok/toktok-stack/677)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @iphydf)

___
*[`WORKSPACE` line 359 at r1](https://reviewable.io/reviews/TokTok/toktok-stack/677#-NjERamyEuoa-0iYOnKX:-NjERamyEuoa-0iYOnKY:bzhxu9t) ([raw file](https://github.com/TokTok/toktok-stack/blob/7cad37cc810f1d3fb9879755c6262ef22a0c9e78/WORKSPACE#L359)):*
> ```Starlark
>     repo = "jedisct1/libsodium",
>     sha256 = "1b72c0cdbc535ce42e14ac15e8fc7c089a3ee9ffe5183399fd77f0f3746ea794",
>     version = "1.0.18",
> ```

there is now a 1.0.19

**Review by iphydf — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TokTok/toktok-stack/677)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @Green-Sky)

___
*[`WORKSPACE` line 359 at r1](https://reviewable.io/reviews/TokTok/toktok-stack/677#-NjERamyEuoa-0iYOnKX:-NjEbB22DnIF0hPSVwYR:b-896fix) ([raw file](https://github.com/TokTok/toktok-stack/blob/7cad37cc810f1d3fb9879755c6262ef22a0c9e78/WORKSPACE#L359)):*
<details><summary><i>Previously, Green-Sky (Erik Scholz) wrote…</i></summary><blockquote>

there is now a 1.0.19
</blockquote></details>

Done.

**Review by Green-Sky — APPROVED** [review]
> Reviewed 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TokTok/toktok-stack/677)* status: :shipit: complete! 1 of 1 approvals obtained

**Pull request merged**
